---
swagger: "2.0"
info:
  description: "Wodby Developer Documentation https://wodby.com/docs/1.0/docs/dev"
  version: "3.1.0"
  title: "Wodby API Client"
  termsOfService: "https://wodby.com/legal"
host: "api.wodby.com"
basePath: "/api/v3"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /orgs:
    get:
      tags:
      - "Organization"
      summary: "Retrieve organizations"
      description: "Retrieve organizations"
      operationId: "getOrgs"
      parameters:
      - name: "name"
        in: "query"
        description: "Organization name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Org"
      security:
      - ApiKeyAuth: []
  /orgs/{id}:
    get:
      tags:
      - "Organization"
      summary: "Retrieve organization"
      description: "Retrieve organization"
      operationId: "getOrg"
      parameters:
      - name: "id"
        in: "path"
        description: "Organization ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Org"
      security:
      - ApiKeyAuth: []
  /apps:
    get:
      tags:
      - "Application"
      summary: "Retrieve applications"
      description: "Retrieve applications"
      operationId: "getApps"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "name"
        in: "query"
        description: "Application name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/App"
      security:
      - ApiKeyAuth: []
    post:
      tags:
      - "Application"
      summary: "Create application"
      description: "Create application"
      operationId: "createApp"
      parameters:
      - in: "body"
        name: "data"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/RequestAppCreate"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTaskApp"
      security:
      - ApiKeyAuth: []
  /apps/{id}:
    get:
      tags:
      - "Application"
      summary: "Retrieve application"
      description: "Retrieve application"
      operationId: "getApp"
      parameters:
      - name: "id"
        in: "path"
        description: "Application ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/App"
      security:
      - ApiKeyAuth: []
    delete:
      tags:
      - "Application"
      summary: "Delete application"
      description: "Delete application"
      operationId: "deleteApp"
      parameters:
      - name: "id"
        in: "path"
        description: "Application ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /apps/{id}/drush-aliases:
    get:
      tags:
      - "Application"
      summary: "Retrieve Drupal application`s instances Drush aliases"
      description: "Retrieve Drupal application`s instances Drush aliases"
      operationId: "getAppDrushAliases"
      parameters:
      - name: "id"
        in: "path"
        description: "Application ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: "Drush aliases in YAML format"
          schema:
            type: "string"
      security:
      - ApiKeyAuth: []
  /instances:
    get:
      tags:
      - "Instance"
      summary: "Retrieve instances"
      description: "Retrieve instances"
      operationId: "getInstances"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "server_id"
        in: "query"
        description: "Server ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "ServerId"
      - name: "app_id"
        in: "query"
        description: "Application ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "AppId"
      - name: "type"
        in: "query"
        description: "Instance type"
        required: false
        type: "string"
        x-exportParamName: "Type_"
      - name: "name"
        in: "query"
        description: "Instance name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Instance"
      security:
      - ApiKeyAuth: []
    post:
      tags:
      - "Instance"
      summary: "Create instance"
      description: "Create instance"
      operationId: "createInstance"
      parameters:
      - in: "body"
        name: "data"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/RequestInstanceCreate"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTaskInstance"
      security:
      - ApiKeyAuth: []
  /instances/{id}:
    get:
      tags:
      - "Instance"
      summary: "Retrieve application instance"
      description: "Retrieve application instance"
      operationId: "getInstance"
      parameters:
      - name: "id"
        in: "path"
        description: "Instance ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Instance"
      security:
      - ApiKeyAuth: []
    delete:
      tags:
      - "Instance"
      summary: "Delete application instance"
      description: "Delete application instance"
      operationId: "deleteInstance"
      parameters:
      - name: "id"
        in: "path"
        description: "Instance ID"
        required: true
        type: "string"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /instances/{id}/deploy:
    post:
      tags:
      - "Instance"
      summary: "Deploy instance"
      description: "Deploy instance"
      operationId: "deployInstance"
      parameters:
      - name: "id"
        in: "path"
        description: "Instance ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      - in: "body"
        name: "data"
        description: ""
        required: false
        schema:
          $ref: "#/definitions/RequestInstanceDeploy"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /instances/{id}/deploy-codebase:
    post:
      tags:
      - "Instance"
      summary: "Deploy instance codebase"
      description: "Deploy instance codebase"
      operationId: "deployInstanceCodebase"
      parameters:
      - name: "id"
        in: "path"
        description: "Instance ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      - in: "body"
        name: "data"
        description: ""
        required: false
        schema:
          $ref: "#/definitions/RequestInstanceDeployCodebase"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /instances/upgrade:
    post:
      tags:
      - "Instance"
      summary: "Upgrade instances"
      description: "Upgrade instances"
      operationId: "upgradeInstances"
      parameters:
      - in: "body"
        name: "data"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/RequestInstancesUpgrade"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /instances/{id}/upgrade:
    post:
      tags:
      - "Instance"
      summary: "Upgrade instance"
      description: "Upgrade instance"
      operationId: "upgradeInstance"
      parameters:
      - name: "id"
        in: "path"
        description: "Instance ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /tasks:
    get:
      tags:
      - "Task"
      summary: "Retrieve tasks"
      description: "Retrieve tasks"
      operationId: "getTasks"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "user_id"
        in: "query"
        description: "User ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "UserId"
      - name: "status"
        in: "query"
        description: "Task status"
        required: false
        type: "string"
        x-exportParamName: "Status"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
      security:
      - ApiKeyAuth: []
  /tasks/{id}:
    get:
      tags:
      - "Task"
      summary: "Retrieve task"
      description: "Retrieve task"
      operationId: "getTask"
      parameters:
      - name: "id"
        in: "path"
        description: "Task ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Task"
      security:
      - ApiKeyAuth: []
  /stacks:
    get:
      tags:
      - "Stack"
      summary: "Retrieve stacks"
      description: "Retrieve stacks"
      operationId: "getStacks"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Stack"
      security:
      - ApiKeyAuth: []
  /stacks/update:
    post:
      tags:
      - "Stack"
      summary: "Update official stacks from upstream"
      description: "Update official stacks from upstream"
      operationId: "updateStacksFromUpstream"
      parameters:
      - in: "body"
        name: "data"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/RequestStacksUpdate"
        x-exportParamName: "Data"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /stacks/{id}:
    get:
      tags:
      - "Stack"
      summary: "Retrieve stack"
      description: "Retrieve stack"
      operationId: "getStack"
      parameters:
      - name: "id"
        in: "path"
        description: "Stack ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Stack"
      security:
      - ApiKeyAuth: []
  /stacks/{id}/update:
    post:
      tags:
      - "Stack"
      summary: "Update official stack from upstream"
      description: "Update official stack from upstream"
      operationId: "updateStackFromUpstream"
      parameters:
      - name: "id"
        in: "path"
        description: "Stack ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/ResponseTask"
      security:
      - ApiKeyAuth: []
  /git-repo:
    get:
      tags:
      - "Git repository"
      summary: "Retrieve git repositories"
      description: "Retrieve git repositories"
      operationId: "getGitRepos"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "name"
        in: "query"
        description: "Git repository name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GitRepo"
      security:
      - ApiKeyAuth: []
  /git-repo/{id}:
    get:
      tags:
      - "Git repository"
      summary: "Retrieve git repository"
      description: "Retrieve git repository"
      operationId: "getGitRepo"
      parameters:
      - name: "id"
        in: "path"
        description: "Git repository ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/GitRepo"
      security:
      - ApiKeyAuth: []
  /servers:
    get:
      tags:
      - "Server"
      summary: "Retrieve servers"
      description: "Retrieve servers"
      operationId: "getServers"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "name"
        in: "query"
        description: "Server name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Server"
      security:
      - ApiKeyAuth: []
  /servers/{id}:
    get:
      tags:
      - "Server"
      summary: "Retrieve server"
      description: "Retrieve server"
      operationId: "getServer"
      parameters:
      - name: "id"
        in: "path"
        description: "Server ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Server"
      security:
      - ApiKeyAuth: []
  /domains:
    get:
      tags:
      - "Domain"
      summary: "Retrieve domains"
      description: "Retrieve domains"
      operationId: "getDomains"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "instance_id"
        in: "query"
        description: "Instance ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "InstanceId"
      - name: "server_id"
        in: "query"
        description: "Server ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "ServerId"
      - name: "status"
        in: "query"
        description: "Domain status"
        required: false
        type: "string"
        x-exportParamName: "Status"
      - name: "type"
        in: "query"
        description: "Domain type"
        required: false
        type: "string"
        x-exportParamName: "Type_"
      - name: "name"
        in: "query"
        description: "Domain name"
        required: false
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Domain"
      security:
      - ApiKeyAuth: []
  /domains/{id}:
    get:
      tags:
      - "Domain"
      summary: "Retrieve domain"
      description: "Retrieve domain"
      operationId: "getDomain"
      parameters:
      - name: "id"
        in: "path"
        description: "Domain ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Domain"
      security:
      - ApiKeyAuth: []
  /backups:
    get:
      tags:
      - "Backup"
      summary: "Retrieve backups by instance"
      description: "Retrieve backups by instance"
      operationId: "getBackups"
      parameters:
      - name: "org_id"
        in: "query"
        description: "Organization ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "OrgId"
      - name: "instance_id"
        in: "query"
        description: "Instance ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "InstanceId"
      - name: "server_id"
        in: "query"
        description: "Server ID"
        required: false
        type: "string"
        format: "uuid"
        x-exportParamName: "ServerId"
      - name: "type"
        in: "query"
        description: "Backup type"
        required: false
        type: "string"
        x-exportParamName: "Type_"
      - name: "status"
        in: "query"
        description: "Backup status"
        required: false
        type: "string"
        x-exportParamName: "Status"
      - name: "days"
        in: "query"
        description: "Get backups for N days"
        required: false
        type: "integer"
        x-exportParamName: "Days"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Backup"
      security:
      - ApiKeyAuth: []
  /backups/{id}:
    get:
      tags:
      - "Backup"
      summary: "Retrieve backup"
      description: "Retrieve backup"
      operationId: "getBackup"
      parameters:
      - name: "id"
        in: "path"
        description: "Backup ID"
        required: true
        type: "string"
        format: "uuid"
        x-exportParamName: "Id"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Backup"
      security:
      - ApiKeyAuth: []
  /user:
    get:
      tags:
      - "User"
      summary: "Retrieve authenticated user"
      description: "Retrieve authenticated user"
      operationId: "getAuthenticatedUser"
      parameters: []
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/User"
      security:
      - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    name: "X-API-KEY"
    in: "header"
definitions:
  User:
    type: "object"
    required:
    - "created"
    - "email"
    - "id"
    - "name"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      name:
        type: "string"
      email:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "User"
    example:
      created: 0
      name: "name"
      last_name: "last_name"
      id: "id"
      first_name: "first_name"
      updated: 6
      email: "email"
  Org:
    type: "object"
    required:
    - "created"
    - "id"
    - "name"
    - "status"
    - "title"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      name:
        type: "string"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "creating"
        - "updating"
        - "deleting"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Org"
    example:
      created: 0
      name: "name"
      id: "id"
      title: "title"
      updated: 6
      status: "ok"
  Task:
    type: "object"
    required:
    - "created"
    - "id"
    - "org_id"
    - "status"
    - "title"
    - "ttl"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      org_id:
        type: "string"
        title: "UUID"
      status:
        type: "string"
        enum:
        - "waiting"
        - "in_progress"
        - "done"
        - "failed"
        - "canceled"
      start:
        type: "integer"
      end:
        type: "integer"
      ttl:
        type: "integer"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Task"
    example:
      org_id: "org_id"
      created: 5
      start: 0
      end: 6
      id: "id"
      title: "title"
      ttl: 1
      updated: 5
      status: "waiting"
  Stack:
    type: "object"
    required:
    - "created"
    - "id"
    - "org_id"
    - "services"
    - "title"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      version:
        type: "string"
        title: "Semantic version or empty"
      new_version:
        type: "string"
        title: "Semantic version or empty"
      revision_number:
        type: "integer"
      services:
        type: "array"
        items:
          $ref: "#/definitions/StackService"
      org_id:
        type: "string"
        title: "UUID"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Stack"
    example:
      revision_number: 0
      org_id: "org_id"
      created: 6
      id: "id"
      new_version: "new_version"
      services:
      - default: true
        name: "name"
        id: "id"
        title: "title"
        required: true
        implementations:
        - default: true
          name: "name"
          title: "title"
          docker_image: "docker_image"
        - default: true
          name: "name"
          title: "title"
          docker_image: "docker_image"
      - default: true
        name: "name"
        id: "id"
        title: "title"
        required: true
        implementations:
        - default: true
          name: "name"
          title: "title"
          docker_image: "docker_image"
        - default: true
          name: "name"
          title: "title"
          docker_image: "docker_image"
      title: "title"
      version: "version"
      updated: 1
  StackService:
    type: "object"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      name:
        type: "string"
      required:
        type: "boolean"
      default:
        type: "boolean"
      implementations:
        type: "array"
        items:
          $ref: "#/definitions/StackServiceImplementation"
    title: "StackService"
    example:
      default: true
      name: "name"
      id: "id"
      title: "title"
      required: true
      implementations:
      - default: true
        name: "name"
        title: "title"
        docker_image: "docker_image"
      - default: true
        name: "name"
        title: "title"
        docker_image: "docker_image"
  StackServiceImplementation:
    type: "object"
    properties:
      title:
        type: "string"
      name:
        type: "string"
      default:
        type: "boolean"
      docker_image:
        type: "string"
    title: "StackService"
    example:
      default: true
      name: "name"
      title: "title"
      docker_image: "docker_image"
  GitRepo:
    type: "object"
    required:
    - "created"
    - "id"
    - "org_id"
    - "status"
    - "title"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      url:
        type: "string"
      org_id:
        type: "string"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "creating"
        - "deleting"
      created:
        type: "integer"
      updated:
        type: "integer"
    example:
      org_id: "org_id"
      created: 0
      id: "id"
      title: "title"
      updated: 6
      url: "url"
      status: "ok"
  App:
    type: "object"
    required:
    - "created"
    - "id"
    - "name"
    - "org_id"
    - "stack_id"
    - "status"
    - "title"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      name:
        type: "string"
      stack_id:
        type: "string"
        title: "UUID"
      org_id:
        type: "string"
        title: "UUID"
      git_repo_id:
        type: "string"
        title: "UUID or empty"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "creating"
        - "deleting"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Application"
    example:
      org_id: "org_id"
      created: 0
      stack_id: "stack_id"
      name: "name"
      git_repo_id: "git_repo_id"
      id: "id"
      title: "title"
      updated: 6
      status: "ok"
  Instance:
    type: "object"
    required:
    - "app_id"
    - "created"
    - "id"
    - "last_deploy"
    - "name"
    - "org_id"
    - "server_id"
    - "stack_id"
    - "stack_rev_number"
    - "stack_version"
    - "status"
    - "title"
    - "updated"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      title:
        type: "string"
      type:
        $ref: "#/definitions/InstanceType"
      org_id:
        type: "string"
        title: "UUID"
      app_id:
        type: "string"
        title: "UUID"
      server_id:
        type: "string"
        title: "UUID"
      stack_rev_number:
        type: "integer"
      stack_version:
        type: "string"
      stack_id:
        type: "string"
        title: "UUID"
      git_repo_id:
        type: "string"
        title: "UUID or empty"
      git_repo_target:
        type: "string"
      has_new_version:
        type: "boolean"
      status:
        type: "string"
        enum:
        - "ok"
        - "unreachable"
        - "error"
        - "creating"
        - "updating"
        - "deleting"
      created:
        type: "integer"
      updated:
        type: "integer"
      last_deploy:
        type: "integer"
    title: "Instance"
    example:
      created: 6
      git_repo_id: "git_repo_id"
      stack_version: "stack_version"
      title: "title"
      type: {}
      server_id: "server_id"
      git_repo_target: "git_repo_target"
      stack_rev_number: 0
      has_new_version: true
      org_id: "org_id"
      stack_id: "stack_id"
      name: "name"
      id: "id"
      app_id: "app_id"
      updated: 1
      last_deploy: 5
      status: "ok"
  InstanceType:
    type: "string"
    title: "Instance Type"
    enum:
    - "dev"
    - "stage"
    - "prod"
  Domain:
    type: "object"
    required:
    - "created"
    - "id"
    - "instance_id"
    - "name"
    - "org_id"
    - "status"
    - "type"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      name:
        type: "string"
      org_id:
        type: "string"
        title: "UUID"
      instance_id:
        type: "string"
        title: "UUID"
      enabled:
        type: "boolean"
      primary:
        type: "boolean"
      protected:
        type: "boolean"
      indexed:
        type: "boolean"
      ssl:
        type: "boolean"
      ssl_required:
        type: "boolean"
      ssl_custom:
        type: "boolean"
      hsts:
        type: "boolean"
      hsts_subdomains:
        type: "boolean"
      redirect_to_www:
        type: "boolean"
      redirect_to_non_www:
        type: "boolean"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "creating"
        - "deleting"
        - "updating"
        - "disabled"
      type:
        type: "string"
        enum:
        - "technical"
        - "user"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Domain"
    example:
      indexed: true
      ssl_custom: true
      created: 0
      ssl_required: true
      hsts_subdomains: true
      redirect_to_www: true
      type: "technical"
      ssl: true
      enabled: true
      instance_id: "instance_id"
      protected: true
      redirect_to_non_www: true
      org_id: "org_id"
      name: "name"
      id: "id"
      hsts: true
      updated: 6
      primary: true
      status: "ok"
  Server:
    type: "object"
    required:
    - "created"
    - "id"
    - "org_id"
    - "status"
    - "title"
    - "updated"
    - "version"
    properties:
      id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      ip_address:
        type: "string"
        title: "IP v4 address or empty"
      version:
        type: "string"
      org_id:
        type: "string"
        title: "UUID"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "creating"
        - "deleting"
        - "updating"
        - "disabled"
        - "unreachable"
        - "initializing"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Server"
    example:
      org_id: "org_id"
      created: 0
      id: "id"
      ip_address: "ip_address"
      title: "title"
      version: "version"
      updated: 6
      status: "ok"
  Backup:
    type: "object"
    required:
    - "created"
    - "id"
    - "instance_id"
    - "org_id"
    - "status"
    - "type"
    - "updated"
    properties:
      id:
        type: "string"
        title: "UUID"
      type:
        type: "string"
        enum:
        - "system"
        - "daily"
        - "manual"
      org_id:
        type: "string"
        title: "UUID"
      instance_id:
        type: "string"
        title: "UUID"
      spent:
        type: "integer"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "waiting"
        - "creating"
        - "restoring"
        - "deleting"
      files:
        $ref: "#/definitions/BackupFiles"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Backup"
    example:
      instance_id: "instance_id"
      org_id: "org_id"
      created: 6
      spent: 0
      files: ""
      id: "id"
      type: "system"
      updated: 1
      status: "ok"
  BackupFile:
    type: "object"
    required:
    - "created"
    - "name"
    - "status"
    - "updated"
    properties:
      name:
        type: "string"
        enum:
        - "database"
        - "files"
      status:
        type: "string"
        enum:
        - "ok"
        - "error"
        - "waiting"
        - "creating"
        - "restoring"
        - "deleting"
      spent:
        type: "integer"
      url:
        type: "string"
      mirrored_url:
        type: "string"
      created:
        type: "integer"
      updated:
        type: "integer"
    title: "Backup file"
  BackupFiles:
    title: "Backup files"
    type: "array"
    items:
      $ref: "#/definitions/BackupFile"
  RequestStacksUpdate:
    type: "object"
    required:
    - "stacks"
    properties:
      stacks:
        type: "array"
        items:
          type: "string"
          title: "UUID"
        maxItems: 50
        minItems: 1
    example:
      stacks:
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
      - "stacks"
  RequestAppCreate:
    type: "object"
    required:
    - "name"
    - "org_id"
    - "server_id"
    - "stack_id"
    properties:
      org_id:
        type: "string"
        title: "UUID"
      title:
        type: "string"
      name:
        type: "string"
        pattern: "^[a-z0-9][a-z0-9-]{0,28}[a-z0-9]$"
      stack_id:
        type: "string"
        title: "UUID"
      docroot:
        type: "string"
      sitename:
        type: "string"
      server_id:
        type: "string"
        title: "UUID"
      instance_type:
        $ref: "#/definitions/InstanceType"
      instance_name:
        type: "string"
        pattern: "^[a-z0-9][a-z0-9-]{0,18}[a-z0-9]$"
      instance_title:
        type: "string"
      services:
        type: "array"
        items:
          $ref: "#/definitions/RequestAppCreate_services"
      deployment_type:
        type: "string"
        default: "vanilla"
        enum:
        - "vanilla"
        - "git"
        - "ci"
      post_deployment:
        type: "boolean"
      git:
        $ref: "#/definitions/RequestAppCreate_git"
    example:
      instance_name: "instance_name"
      instance_title: "instance_title"
      services:
      - enable: true
        implementation: "nginx-1-15"
        name: "http-server"
      - enable: true
        implementation: "nginx-1-15"
        name: "http-server"
      title: "title"
      server_id: "server_id"
      deployment_type: "vanilla"
      git:
        repo_id: "repo_id"
        tree_ish: "tree_ish"
      org_id: "org_id"
      stack_id: "stack_id"
      name: "name"
      sitename: "sitename"
      post_deployment: true
      docroot: "docroot"
      instance_type: {}
  RequestInstanceCreate:
    type: "object"
    required:
    - "app_id"
    - "name"
    - "server_id"
    - "type"
    properties:
      app_id:
        type: "string"
        title: "UUID"
      server_id:
        type: "string"
        title: "UUID"
      type:
        $ref: "#/definitions/InstanceType"
      name:
        type: "string"
        pattern: "^[a-z0-9][a-z0-9-]{0,18}[a-z0-9]$"
      title:
        type: "string"
      post_deployment:
        type: "boolean"
      git:
        $ref: "#/definitions/RequestInstanceCreate_git"
    example:
      git:
        tree_ish: "tree_ish"
      name: "name"
      post_deployment: true
      server_id: "server_id"
      type: {}
      title: "title"
      app_id: "app_id"
  RequestInstanceDeploy:
    type: "object"
    properties:
      post_deployment:
        type: "boolean"
    example:
      post_deployment: true
  RequestInstanceDeployCodebase:
    type: "object"
    properties:
      git:
        $ref: "#/definitions/RequestInstanceCreate_git"
      post_deployment:
        type: "boolean"
    example:
      git:
        tree_ish: "tree_ish"
      post_deployment: true
  RequestInstancesUpgrade:
    type: "object"
    required:
    - "instances"
    properties:
      instances:
        type: "array"
        items:
          type: "string"
          title: "UUID"
        maxItems: 50
        minItems: 1
    example:
      instances:
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
      - "instances"
  ResponseTask:
    type: "object"
    required:
    - "task"
    properties:
      task:
        $ref: "#/definitions/Task"
    example:
      task:
        org_id: "org_id"
        created: 5
        start: 0
        end: 6
        id: "id"
        title: "title"
        ttl: 1
        updated: 5
        status: "waiting"
  ResponseTaskApp:
    type: "object"
    required:
    - "app"
    - "task"
    properties:
      app:
        $ref: "#/definitions/App"
      task:
        $ref: "#/definitions/Task"
    example:
      app:
        org_id: "org_id"
        created: 0
        stack_id: "stack_id"
        name: "name"
        git_repo_id: "git_repo_id"
        id: "id"
        title: "title"
        updated: 6
        status: "ok"
      task:
        org_id: "org_id"
        created: 5
        start: 0
        end: 6
        id: "id"
        title: "title"
        ttl: 1
        updated: 5
        status: "waiting"
  ResponseTaskInstance:
    type: "object"
    required:
    - "instance"
    - "task"
    properties:
      instance:
        $ref: "#/definitions/Instance"
      task:
        $ref: "#/definitions/Task"
    example:
      instance:
        created: 6
        git_repo_id: "git_repo_id"
        stack_version: "stack_version"
        title: "title"
        type: {}
        server_id: "server_id"
        git_repo_target: "git_repo_target"
        stack_rev_number: 0
        has_new_version: true
        org_id: "org_id"
        stack_id: "stack_id"
        name: "name"
        id: "id"
        app_id: "app_id"
        updated: 1
        last_deploy: 5
        status: "ok"
      task:
        org_id: "org_id"
        created: 5
        start: 0
        end: 6
        id: "id"
        title: "title"
        ttl: 1
        updated: 5
        status: "waiting"
  RequestAppCreate_services:
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "http-server"
      implementation:
        type: "string"
        example: "nginx-1-15"
      enable:
        type: "boolean"
    example:
      enable: true
      implementation: "nginx-1-15"
      name: "http-server"
  RequestAppCreate_git:
    required:
    - "repo_id"
    properties:
      repo_id:
        type: "string"
        title: "UUID"
      tree_ish:
        type: "string"
        description: "Commit, branch or tag"
    example:
      repo_id: "repo_id"
      tree_ish: "tree_ish"
  RequestInstanceCreate_git:
    properties:
      tree_ish:
        type: "string"
        description: "Commit, branch or tag"
    example:
      tree_ish: "tree_ish"
externalDocs:
  description: "Wodby Developer Documentation"
  url: "https://wodby.com/docs/1.0/docs/dev"
